In [15]:
# Numpy Task Part 1  Ashley Eshghi
import numpy
vector = numpy.arange(10, 50)
print("Original vector:")
print(vector)
reverse_vector = vector[::-1]
print("Reversed vector:")
print(reverse_vector)

Original vector:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
Reversed vector:
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [16]:
array = numpy.random.random((5, 5))
print("Array:")
print(array)
print("Minimum:", array.min())
print("Maximum:", array.max())

Array:
[[0.10941989 0.10993178 0.52109803 0.65483567 0.54613079]
 [0.86720052 0.96018149 0.60987582 0.8685656  0.36615705]
 [0.9215569  0.28894675 0.40119965 0.78671506 0.97214249]
 [0.31410219 0.26690931 0.08494041 0.88277537 0.64291498]
 [0.85444897 0.07291231 0.75088566 0.87128454 0.23786816]]
Minimum: 0.07291230717693487
Maximum: 0.9721424879731798


In [17]:
matrix = numpy.random.random((5, 5))
print("Original matrix:")
print(matrix)
normalized = (matrix - matrix.min()) / (matrix.max() - matrix.min())
print("Normalize:")
print(normalized)

Original matrix:
[[0.57421665 0.47850634 0.52110773 0.03462711 0.33791117]
 [0.69737813 0.02001084 0.52270869 0.97751727 0.66540467]
 [0.53704104 0.47669375 0.69017719 0.03942289 0.59179721]
 [0.94852858 0.70786568 0.78475152 0.42375602 0.76305631]
 [0.97938065 0.01032216 0.53263334 0.458842   0.5054193 ]]
Normalize:
[[0.58189933 0.48313304 0.52709467 0.02508099 0.33804875]
 [0.70899329 0.00999804 0.52874675 0.99807712 0.67599893]
 [0.54353672 0.48126258 0.70156243 0.0300299  0.60004123]
 [0.96816283 0.71981571 0.79915647 0.42663458 0.77676854]
 [1.         0.         0.53898829 0.46284083 0.51090532]]


In [18]:
first = numpy.random.random((5, 3))
second = numpy.random.random((3, 2))
print("Frist Matrix:")
print(first)
print("Matrix B:")
print(second)
result = numpy.dot(first,second)
print("Second Matrix:")
print(result)

Frist Matrix:
[[0.61296685 0.8789939  0.47122106]
 [0.55972472 0.60110554 0.83157533]
 [0.65144731 0.89793992 0.84486622]
 [0.56221335 0.8425573  0.81291645]
 [0.21460127 0.83916564 0.37483734]]
Matrix B:
[[0.20630105 0.45657417]
 [0.88187465 0.56590878]
 [0.99227123 0.49676412]]
Second Matrix:
[[1.36919724 1.01138091]
 [1.47071981 1.00882354]
 [1.76460115 1.22528533]
 [1.66564873 1.13733039]
 [1.15625168 0.75907834]]


In [19]:
today = numpy.datetime64('today','D')
yesterday = today - numpy.timedelta64(1,'D')
tomorrow = today + numpy.timedelta64(1,'D')
print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)

Yesterday: 2026-10-05
Today: 2026-10-06
Tomorrow: 2026-10-07


In [20]:
array = numpy.random.random(5) * 10
print("Original:")
print(array)
print("Method 1:", array - array % 1)
print("Method 2:", array // 1)
print("Method 3:", numpy.floor(array))
print("Method 4:", array.astype(int))
print("Method 5:", numpy.trunc(array))

Original:
[2.53293403 2.50070358 4.40462201 0.31462092 8.43644772]
Method 1: [2. 2. 4. 0. 8.]
Method 2: [2. 2. 4. 0. 8.]
Method 3: [2. 2. 4. 0. 8.]
Method 4: [2 2 4 0 8]
Method 5: [2. 2. 4. 0. 8.]


In [21]:
colorarray= [
    ('position', [('x', float), ('y', float)]),
    ('color', [('r', int), ('g', int), ('b', int)])
]
array = numpy.zeros(5, dtype=colorarray)
print(array)

[((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0))
 ((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0))]
