In [22]:
# Numpy Task Part 2  Ashley Eshghi
import numpy
def generate_numbers():
    for i in range(10):
        yield i
array = numpy.array(list(generate_numbers()))
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [23]:
A = numpy.random.randint(0, 10, (3, 3))
B = numpy.random.randint(0, 10, (3, 3))
print("Array A:")
print(A)
print("Array B:")
print(B)
equal = numpy.array_equal(A, B)
print("Are they equal?", equal)

Array A:
[[7 2 1]
 [7 9 9]
 [4 3 9]]
Array B:
[[9 5 6]
 [7 4 7]
 [7 5 5]]
Are they equal? False


In [24]:
coordinates = numpy.random.random((100, 2))
distances = numpy.zeros((100, 100))
for i in range(100):
    for j in range(100):
        x1 = coordinates[i][0]
        y1 = coordinates[i][1]
        x2 = coordinates[j][0]
        y2 = coordinates[j][1]
        distances[i][j] = numpy.sqrt((x1 - x2)**2 + (y1 - y2)**2)
print("Coordinates:")
print(coordinates)
print("Distances:")
print(distances)

Coordinates:
[[0.02477385 0.12197066]
 [0.77477484 0.53557153]
 [0.03145597 0.8422352 ]
 [0.06158202 0.32820518]
 [0.12402996 0.7003225 ]
 [0.02433799 0.7245427 ]
 [0.57754881 0.61252202]
 [0.9279964  0.98847003]
 [0.89751448 0.96559257]
 [0.80354556 0.39101638]
 [0.36694187 0.64762084]
 [0.78029216 0.50131399]
 [0.94016437 0.00272301]
 [0.10747229 0.62932834]
 [0.78197808 0.85235784]
 [0.87021981 0.32195912]
 [0.90423497 0.21727819]
 [0.38404742 0.58113125]
 [0.95275189 0.4957215 ]
 [0.92755962 0.23016471]
 [0.99580726 0.41542528]
 [0.94141172 0.97779979]
 [0.78589124 0.67678347]
 [0.74974782 0.75869298]
 [0.14804849 0.17827956]
 [0.96403902 0.71849932]
 [0.66407661 0.05215577]
 [0.09909478 0.26139783]
 [0.50195159 0.92432632]
 [0.96432848 0.32703048]
 [0.45297293 0.66557487]
 [0.19801759 0.98647951]
 [0.2055657  0.5799438 ]
 [0.97880536 0.96170745]
 [0.12234724 0.99631645]
 [0.23374359 0.5740148 ]
 [0.7980053  0.70038979]
 [0.25437481 0.09373538]
 [0.47799326 0.41510397]
 [0.59954176

In [25]:
matrix = numpy.random.random((5, 5))
print("Original:")
print(matrix)
row_means = matrix.mean(axis=1)
result = matrix - row_means[:, None]
print("Matrix after subtracting row means:")
print(result)

Original:
[[0.02078161 0.07493773 0.61166024 0.59962755 0.1129042 ]
 [0.58579762 0.96481614 0.73733343 0.58454435 0.37410914]
 [0.91012869 0.87393529 0.58701691 0.08184419 0.23941853]
 [0.84561692 0.5267972  0.8381074  0.80560847 0.06589263]
 [0.53563082 0.81283293 0.92195794 0.9372039  0.20916311]]
Matrix after subtracting row means:
[[-0.26320066 -0.20904454  0.32767798  0.31564528 -0.17107806]
 [-0.06352251  0.315496    0.0880133  -0.06477579 -0.275211  ]
 [ 0.37165996  0.33546657  0.04854819 -0.45662453 -0.29905019]
 [ 0.2292124  -0.08960732  0.22170287  0.18920394 -0.55051189]
 [-0.14772692  0.12947519  0.2386002   0.25384616 -0.47419463]]


In [26]:
array = numpy.array([
    [5, 2, 8],
    [1, 7, 4],
    [3, 1, 6],
    [2, 9, 5]
])
print("Original:")
print(array)
n = 1
sort = array[array[:, n].argsort()]
print("Sorted array:")
print(sort)

Original:
[[5 2 8]
 [1 7 4]
 [3 1 6]
 [2 9 5]]
Sorted array:
[[3 1 6]
 [5 2 8]
 [1 7 4]
 [2 9 5]]


In [27]:
matrix = numpy.random.randint(0, 10, (4, 4))
print("Matrix:")
print(matrix)
rank = numpy.linalg.matrix_rank(matrix)
print("Rank:", rank)

Matrix:
[[3 5 4 4]
 [1 0 2 8]
 [4 0 5 2]
 [9 7 2 7]]
Rank: 4


In [28]:
array = numpy.random.randint(0, 10, (16, 16))
print("Original:")
print(array)
blocks = array.reshape(4, 4, 4, 4)
block_sum = blocks.sum(axis=(1, 3))
print("block sum:")
print(block_sum)

Original:
[[7 8 6 0 1 4 4 1 5 1 0 8 1 0 0 3]
 [0 3 4 6 7 1 1 4 3 7 1 9 0 5 1 4]
 [0 3 7 8 8 2 4 4 5 6 0 5 6 0 5 2]
 [8 1 3 0 3 1 6 0 6 1 0 2 5 9 2 2]
 [2 7 5 2 9 6 6 3 3 3 5 1 5 9 3 3]
 [6 3 1 9 2 1 8 7 0 9 4 1 6 9 9 0]
 [0 7 5 8 9 7 4 4 6 9 8 7 3 1 7 7]
 [2 1 5 3 5 8 7 5 7 7 5 1 9 1 7 5]
 [6 3 4 9 8 6 9 2 8 2 2 7 0 1 7 3]
 [3 5 5 7 3 3 0 2 8 8 5 3 1 2 0 0]
 [2 6 5 9 9 6 2 0 6 8 1 6 9 4 0 1]
 [0 3 2 6 4 6 0 2 5 7 1 4 0 1 3 5]
 [2 9 7 0 6 6 6 4 7 4 6 3 7 6 1 9]
 [6 3 4 8 7 8 9 5 5 2 9 1 2 6 6 3]
 [0 4 3 5 4 4 3 9 2 6 2 7 5 5 6 2]
 [2 2 9 3 1 9 3 5 4 1 8 6 5 9 7 8]]
block sum:
[[64 51 59 45]
 [66 91 76 84]
 [75 62 81 37]
 [67 89 73 87]]
